config/routes.rb
Vibrant::Application.routes.draw do

  resources :jobs
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :tokens,:only => [:create, :destroy]
  resources :accounts

  require 'sidekiq/web'
  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  root :to => "info#welcome" # a temporary redirection, should be to welcome

  post 'jobs/search(.:format)', :to => 'jobs#search'
  post 'left/view/:id', :to => 'jobs#leftstream'
  get 'left/view/:id', :to => 'jobs#leftstream'

  post 'jobs/new', :to => 'jobs#new'
  post 'show_all', :to => 'jobs#show_all'
  post 'users/toggle/:id', :to => 'user#toggle_left'
  post 'accounts/arrears/:id', :to => 'accounts#toggle_arrears'
  post 'accounts/:id', :to => 'accounts#show'

  put  'jobs/recreate/:id(.:format)', :to => 'jobs#recreate'
  put  'delete/:id(.:format)', :to => 'jobs#destroy' # as delete doesn't seem to offer the ability to authenticate

  get  'jobs/new', :to => 'jobs#new'
  get  'jobs/new/:type', :to => 'jobs#new'
  get  'jobs/search(.:format)', :to => 'jobs#index'
  get  'download/:id', :to => 'jobs#download'
  get  'download/infile/:id', :to => 'jobs#get_infile'
  get  'download/coords/:id(.:format)', :to => 'jobs#download_coords'
  get  'show_all', :to => 'jobs#show_all'
  get  'show_token', :to => 'user#show_token'
  get  'change_token', :to => 'user#change_token'
  get  'users/list', :to => 'user#list_users'
  get  'users/show/:id', :to => 'user#show_user'
  post  'users/show/:id', :to => 'user#show_user'
  get  'users/find', :to => 'user#find_users'
  post  'users/find', :to => 'user#find_users'
  get  'stats', :to => 'user#stats'
  get 'jobs/toggle/:id', :to => 'jobs#toggle_public'
  get 'jobs/status/:id', :to => 'jobs#get_status'

  get  'routes', :to => 'info#routes'
  get  'docs', :to => 'info#docs'
  get  'left', :to => 'info#welcome'
  get  'home', :to => 'info#welcome'
  get  'privacy-policy', :to => 'info#privacy'
  get  'faq', :to => 'info#faq'
  get  'parameters/:type', :to => 'info#parameters'
  get  'types', :to => 'info#job_types'
  post  'types', :to => 'info#job_types'
  get  'information', :to => 'info#information'
  get  'undefined', :to => 'info#welcome'
  get  'inspect/:type/:id', :to => 'info#inspect'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/user.rb
class User
  include MongoMapper::Document         

  devise :database_authenticatable, :token_authenticatable, :confirmable, :recoverable, :registerable, :rememberable, :trackable, :validatable, :lockable#, :shibboleth_authenticatable

  # jobs assigned to user, with a particular user for all the scratchpad jobs
  # only one account per user at the moment
  many :jobs

  before_validation :set_defaults, :on => :create
  before_validation :email_admin, :on => :create
  before_destroy :purge_from_account

  def set_defaults
    self.admin = false
    account = Account.first(:name => 'Default')
    self.account = account.id
    account.users << self.id
    account.save!
  end

  def purge_from_account
    account = Account.find(self.account)
    account.users.delete(self.id)
    account.save!
  end

  def email_admin
     UserMailer.new_user(self).deliver
  end

  # is the password confirmation required here? 
  key :email, String, :required => true, :unique => true
  key :admin, Boolean, :default => false
  key :runs, Hash, :required => false # how many times has a user run each type of job?
  key :notify, Boolean, :default => true # do users want to receive e-mails or not?
  key :account, String
  timestamps!

  
  # http://technicaldebt.com/?p=1089
  def self.create_indexes
    self.ensure_index(:email, :unique => true)
  end

  def allowed?(email)
    begin    
      allowed_users = IO.readlines("#{Rails.root}/allowed_users").to_a.collect {|x| x.chomp!}  
    rescue    
      allowed_users = Array.new    
      Rails.logger.error("#{Rails.root}/allowed_users is missing.")  
    end
    if allowed_users.include?(email)
      return true
    end
    return false
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_allowed, :only => [:show_token,:change_token]
  layout :resolve_layout

  # a couple of methods for showing server admins
  # their auth token and letting them change it
  def show_token
    @token = current_user.authentication_token
    if @token.nil?
      flash[:alert] = "Token not available."      
      redirect_to :controller => 'info', :action => 'welcome'
    end
  end

  def change_token
    @user = current_user
    if @user.authentication_token.nil?
      flash[:alert] = "Action not allowed."      
      redirect_to :controller => 'info', :action => 'welcome' and return
    end
    @user.reset_authentication_token 
    if @user.save
      flash[:notice] = "Token changed."      
      redirect_to :controller => 'user', :action => 'show_token'
    else
      flash[:alert] = "Failed to change token."      
      redirect_to :controller => 'info', :action => 'welcome' 
    end

  end

  # a means for admins to see all jobs on the system
  def list_users
    if !current_user.admin?
      redirect_to :jobs and return
    end

    @users = User.paginate :page => params[:page], :order => 'created_at DESC'

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @jobs }
      format.json  { render :json => @jobs }
    end

  end

  def find_users
    if !current_user.admin?
      redirect_to :jobs and return
    end
    if request.post?
      begin
        re = Regexp.new(Regexp.escape(params[:email]), 'i')
        @users = User.all(:email => re)
      rescue
        flash[:alert] = "User not found"
        redirect_to '/users/find'
      end
    end
  end

  # edit a single user in order to add them to a group,
  # and so on...
  def show_user
    if !current_user.admin?
      redirect_to :jobs and return
    end
    @user = User.find(params[:id])
    if request.post?
      # process the form and save the user
      begin
      @account = Account.find(params[:account][:id])
      old_account = Account.first(:users => @user.id)
      old_account.users.delete(@user.id)
      old_account.save!
      @account.users << @user.id
      @account.users.uniq!
      @user.account = @account.id
      rescue
        Rails.logger.error("Failed to change account for user: #{@user.id}")
        redirect_to :controller => '/user', :action => 'show_user', :id => @user.id
        return
      end
      # This should be a unique key if I understand the mongo_mapper documentation
      # correctly, but it seems happy to have the same value inserted multiple times.
      # I'm damned if I know why...
      if @account.save! and @user.save!
        flash[:notice] = "Account updated successfully!"
      else
        flash[:alert] = "Error updating account!"
      end
      redirect_to :controller => '/user', :action => 'show_user', :id => @user.id
    else
      @account = Account.first(:users => @user.id)
    end
  end

  
  def stats
    if !current_user.admin?
      redirect_to :jobs and return
    end
    # find all users and count how many jobs they've done
    @output = Hash.new
    users = User.all
    Job.types.each {|k,v| 
      value = 0
      users.each do |u|
        if u.runs[v].blank?
          u.runs[v] = 0
        else
          value += u.runs[v]        
        end
      end
      @output[k] = value
    } 
  end

end

app/helpers/user_helper.rb
module UserHelper

  def statcolour(flag)
    if flag.class == TrueClass
      return "#33CC33"
    else
      return "#FF3300"
    end
  end

  def stattext(flag)
    if flag.class == TrueClass
      return "Yes"
    else
      return "No"
    end
  end

  def buttong(flag)
    if flag.class == TrueClass
      return "btn btn-success"
    else
      return "btn btn-danger"
    end
  end

  def hostname(ip)
    if ip.nil?
      return "User has never logged in." 
    else
      addr = `host-woods #{ip}`
      if addr.nil?
        return "No information"
      else
        return addr.gsub(/\n/,"<br/>")
      end
    end
  end

end

app/views/user/find_users.html.erb
<% if !request.post? -%>
  <div class="oboe-services-header"><span class="content-section users-section"><span class="header-text">Find Users</span></span></div>

<p>Find users by e-mail: </p>
<%= form_tag '/users/find' do -%>
  <%= search_field_tag :email -%>
  <%= submit_tag 'Submit' %>
<% end -%>

<% else -%>
<div class="oboe-services-header"><span class="content-section users-section"><span class="header-text">Listing Users</span></span></div>

<table class="table table-condensed" cellpadding="2">
  <tr valign="top" class="ListLine0">
    <th>E-mail</th>
    <th>Account</th>
    <th>Created</th>
    <th>Last login</th>
    <th>IP address</th>
    <th>Token enabled?</th>
    <th>Admin?</th>
  </tr>

  <% 
    odd_or_even = 0
    @users.each do |user| 
      odd_or_even = 1 - odd_or_even
      @account = Account.find(user.account)
  %>
  <tr valign="top" class="ListLine<%= odd_or_even -%>">
    <td><%= link_to user.email, :controller => 'user', :action => 'show_user', :id => user.id -%></td>
    <td><%= link_to @account.name, :controller => 'accounts', :action => 'show', :id => user.account -%>
    <td><%= user.created_at %></td>
    <td><%= user.last_sign_in_at || "N/A" %></td>
    <td><%= user.last_sign_in_ip || "N/A" %></td>
    <td align="center"><%= "<span class='label label-success'>yes</span>".html_safe if !user.authentication_token.nil? %></td>
    <td align="center"><%= "<span class='label label-success'>yes</span>".html_safe if user.admin == true %></td>
  </tr>
<% end %>
</table>

<br><%= link_to 'Find users', '/users/find' -%>

<% end -%>

app/views/user/list_users.html.erb
<div class="oboe-services-header"><span class="content-section users-section"><span class="header-text">Listing Users</span></span></div>

<table class="table table-condensed" cellpadding="2">
  <tr valign="top" class="ListLine0">
    <th>E-mail</th>
    <th>Account</th>
    <th>Created</th>
    <th>Last login</th>
    <th>IP address</th>
    <th>Token enabled?</th>
    <th>Admin?</th>
  </tr>

  <% 
    odd_or_even = 0
    @users.each do |user| 
      odd_or_even = 1 - odd_or_even
      @account = Account.find(user.account)
  %>
  <tr valign="top" class="ListLine<%= odd_or_even -%>">
    <td><%= link_to user.email, :controller => 'user', :action => 'show_user', :id => user.id -%></td>
    <td><%= link_to @account.name, :controller => 'accounts', :action => 'show', :id => user.account -%>
    <td><%= user.created_at %></td>
    <td><%= user.last_sign_in_at || "N/A" %></td>
    <td><%= user.last_sign_in_ip || "N/A" %></td>
    <td align="center"><%= "<span class='label label-success'>yes</span>".html_safe if !user.authentication_token.nil? %></td>
    <td align="center"><%= "<span class='label label-success'>yes</span>".html_safe if user.admin == true %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @users -%>
<br><%= page_entries_info @users -%>
<br><%= link_to 'Find users', '/users/find' -%>

app/views/user/show_token.html.erb
<h1>Authentication token</h1>

<p>Your account has an authentication token, the purpose of which is to allow access for servers via the API described in the <%= link_to 'documentation', :controller => 'info', :action => 'docs' -%>. The value of the token is shown below. 

<pre>
<%= current_user.authentication_token -%>
</pre>

<p>To change the token value, click <%= link_to 'here', :controller => 'user', :action => 'change_token' -%>.

<p>Or, you may Return to the <%= link_to "job listing", jobs_path -%>. 

app/views/user/show_user.html.erb
<h1>User Information</h1>

<p>User's account: <%= @user.email -%>
<% if !@account.blank? -%>
  <br>User belongs to account: <%= link_to @account.name, :controller => 'accounts', :action => 'show', :id => @account.id -%>
<% end -%>
</p>
<br/>

<p>Change user account: 
<%= form_tag :controller => 'user', :action => 'show_user' do -%>
  <%= select("account", "id", Account.all.collect {|a| [ a.name, a.id ] }, { :include_blank => false }) -%>
  <%= submit_tag 'Submit' %>
<% end -%>
</p>
<br/>

<h2>User's IP address:</h2>
<p><%= hostname(@user.last_sign_in_ip).html_safe -%>

app/views/user/stats.html.erb
<div class="oboe-services-header"><span class="content-section  job-section"><span class="header-text">Job status</span></span></div>


<table class="table table-condensed" cellpadding="2">
  <tr valign="top" class="ListLine0">
    <th>Job</th>
    <th>Current</th>
    <th>Total run</th>
  </tr>

  <% 
    odd_or_even = 0
    @output.each do |k,v| 
      odd_or_even = 1 - odd_or_even
  %>
  <tr valign="top" class="ListLine<%= odd_or_even -%>">
    <td><%= k %></td>
    <td><span class="badge badge-info"><%= Job.all(:type => Job.types[k]).size %></span></td>
    <td><span class="badge badge-info"><%= v %></span></td>
  </tr>
<% end %>
</table>