config/routes.rb
Vibrant::Application.routes.draw do

  resources :jobs
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :tokens,:only => [:create, :destroy]
  resources :accounts

  require 'sidekiq/web'
  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  root :to => "info#welcome" # a temporary redirection, should be to welcome

  post 'jobs/search(.:format)', :to => 'jobs#search'
  post 'left/view/:id', :to => 'jobs#leftstream'
  get 'left/view/:id', :to => 'jobs#leftstream'

  post 'jobs/new', :to => 'jobs#new'
  post 'show_all', :to => 'jobs#show_all'
  post 'users/toggle/:id', :to => 'user#toggle_left'
  post 'accounts/arrears/:id', :to => 'accounts#toggle_arrears'
  post 'accounts/:id', :to => 'accounts#show'

  put  'jobs/recreate/:id(.:format)', :to => 'jobs#recreate'
  put  'delete/:id(.:format)', :to => 'jobs#destroy' # as delete doesn't seem to offer the ability to authenticate

  get  'jobs/new', :to => 'jobs#new'
  get  'jobs/new/:type', :to => 'jobs#new'
  get  'jobs/search(.:format)', :to => 'jobs#index'
  get  'download/:id', :to => 'jobs#download'
  get  'download/infile/:id', :to => 'jobs#get_infile'
  get  'download/coords/:id(.:format)', :to => 'jobs#download_coords'
  get  'show_all', :to => 'jobs#show_all'
  get  'show_token', :to => 'user#show_token'
  get  'change_token', :to => 'user#change_token'
  get  'users/list', :to => 'user#list_users'
  get  'users/show/:id', :to => 'user#show_user'
  post  'users/show/:id', :to => 'user#show_user'
  get  'users/find', :to => 'user#find_users'
  post  'users/find', :to => 'user#find_users'
  get  'stats', :to => 'user#stats'
  get 'jobs/toggle/:id', :to => 'jobs#toggle_public'
  get 'jobs/status/:id', :to => 'jobs#get_status'

  get  'routes', :to => 'info#routes'
  get  'docs', :to => 'info#docs'
  get  'left', :to => 'info#welcome'
  get  'home', :to => 'info#welcome'
  get  'privacy-policy', :to => 'info#privacy'
  get  'faq', :to => 'info#faq'
  get  'parameters/:type', :to => 'info#parameters'
  get  'types', :to => 'info#job_types'
  post  'types', :to => 'info#job_types'
  get  'information', :to => 'info#information'
  get  'undefined', :to => 'info#welcome'
  get  'inspect/:type/:id', :to => 'info#inspect'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE  html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-gb">

<head>
  <title>OeRC Batch Operation Engine</title>
  <meta name="keywords" content="Vibrant,OeRC" />
  <%= stylesheet_link_tag "oxbluetwo/basic" , :media => 'all'%>
  <%= stylesheet_link_tag "oxbluetwo/layout", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "oxbluetwo/lookandfeel", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "oxbluetwo/mainnav", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "oxbluetwo/print", :media => 'print' %>
  <%= stylesheet_link_tag "oxbluetwo/table", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "oxbluetwo/custom", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "jquery-ui-timepicker-addon.css" %>
  <%= stylesheet_link_tag "jquery-ui.css" %>
  <%= javascript_include_tag :defaults -%>
  <%= csrf_meta_tag %>
  <%= gmaps_header(@headers).html_safe -%>
</head>
<body>

<div id="all">

<div id="header">
</div> <!-- header div -->

<div id="content">

<% if flash[:notice] -%>
<p id="notice"><%= notice %></p>
<% end -%>
<% if flash[:alert] -%>
<p id="alert"><%= alert %></p>
<% end -%>

<%= yield %>

</div> <!-- content div -->

<div id="mainnav">

<ul class="hmenu">
<li><%= link_to 'Home',  :controller => '/info', :action => 'welcome'  -%></li>
<li><%= link_to 'My analyses', :controller => '/jobs', :action => 'index' -%></li>
<%= render 'devise/menu/registration_items' -%>
<%= render 'devise/menu/login_items' -%>
<% if current_user.try(:admin?) -%>
  <li><%= link_to 'Jobs', show_all_path -%></li>
  <li><a href='/users/list'>Users</a></li>
  <li><a href='/stats'>Stats</a></li>
  <li><a href='/accounts'>Accounts</a></li>
<% end -%>
<% if current_user -%>
<% if current_user.allowed?(current_user.email) -%>
  <li><a href='/show_token'>Token</a></li>
<% end -%>
<% end -%>

</ul>

</div> <!-- mainnav div -->

<div id="footer">
  &copy;  University of Oxford 2011
  <a id="vibrant-logo" href="http://vbrant.eu" title="ViBRANT Homepage"><img  alt ="ViBRANT Logo" src="/images/acquia_prosper_logo.png" /></a>
</div> 
  <!-- footer div ends -->
</div> <!-- all div ends -->


</body>
</html>

app/views/layouts/left.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Local Ecological Footprinting Tool</title>
  <%= stylesheet_link_tag 'scaffold','left' %>
  <%= stylesheet_link_tag "jquery-ui-timepicker-addon.css" %>
  <%= stylesheet_link_tag "jquery-ui.css" %>
  <%= javascript_include_tag :defaults -%>
  <%= csrf_meta_tag %>
  <%= gmaps_header(@headers).html_safe -%>
</head>
<body onload="initialize()">
<div id="body-wrapper">
<div id="header-wrapper">
  <div id="header-inner">
    <div id="header-top">
      <div id="logo"><img src="/images/LEFT-logo.gif" alt="LEFT"></div>
      <div id="others"><a href="http://www.statoil.com/" target="_blank"><img src="/images/header-logo-statoil.gif" alt="STATOIL" border="0"></a> <a href="http://www.biodiversity.ox.ac.uk/" target="_blank"><img src="/images/header-logo-bio.jpg" alt="BIO" border="0"></a><a href="http://www.ox.ac.uk/" target="_blank"><img src="/images/header-logo-oxforduniversity.gif" alt="Oxford University" border="0"></a> <a href="http://www.oerc.ox.ac.uk/" target="_blank"><img src="/images/header-logo-oerc.gif" alt="OERC" border="0"></a>  </div>
    </div>
  </div>
</div>
<div id="main-content">

  <div id="main-inner">
    <div class="topcol">&nbsp;</div>

    <% if flash[:notice] -%>
      <p id="notice"><%= notice %></p>
    <% end -%>
    <% if flash[:alert] -%>
      <p id="alert"><%= alert %></p>
    <% end -%>
    <%= yield %>
  </div>
  <div id="sidebar">
    <div class="topcol">&nbsp;</div>
        <h2>Navigate</h2>
    <ul class="hmenu">
      <li><%= link_to 'Home',  :controller => '/info', :action => 'welcome_left'  -%></li>
      <li><%= link_to 'My analyses', :controller => '/jobs', :action => 'index' -%></li>
       <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
    </ul>
  </div>
</div>
<!-- <%= cookie_waffle.html_safe -%> -->
<!-- end main-inner -->
</body>
</html>

app/views/layouts/logrender.html.erb
<html>
  <head>
    <title>Logfile for job <%= @id -%></title>
  </head>
<body>
  <pre>
<%= yield %>
  </pre>
</html>

app/views/layouts/newleft.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <!--TODO SHOW LOGIN/OUT & MY ANALYSES IMAGES AT THE TOP. -->
    <!--TODO ADD LOGOS FOR EACH OF THE FUNDERS AT THE BOTTOM OF THE PAGE.-->
    <title>LEFT | Local Ecological Footprinting Tool</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= javascript_include_tag :defaults -%>

    <script type="text/javascript" src="/assets/js/jquery-1.4.1-and-plugins.min.js"></script>
    <script type="text/javascript" src="/assets/bootstrap/js/bootstrap.min.js"></script>

    <link rel="shortcut icon" href="/assets/img/favicon.ico">
    <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.css"/>

    <link rel="stylesheet" href="/assets/css/leftstyle.css"/>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,300' rel='stylesheet' type='text/css'>
    

    <meta property="og:type" content="OBOE"/>
    <meta property="og:site_name" content="OBOE"/>
    <meta property="og:description" content="OBOE"/>


    <!-- this is the new left layout -->
    <%= csrf_meta_tag %>
    <%= gmaps_header(@headers).html_safe -%>

    <style type="text/css">
        html {
            height: 100%
        }

        #map {
            height: 600px;
        }
    </style>
</head>

<body class="home" onload="initialize();">
<div id="container">
    <div id="hd">
        <div id="hd_bar"></div>
        <div id="hd_nav">
            <div id="hd_nav_wrapper" class="clearfix">
                <ul id="site_nav" class="clearfix">
                    <li id="site_nav_home" class="selected"><a href="/left" class="trackedLink">
                        <span class="label">Local Ecological Footprinting Tool</span></a>
                    </li>
                </ul>

                <ul id="external_links" class="ext_nav">
                <li id="site_nav_new_analysis">
                        <a href="/jobs/new/left" class="navigation-button navigation-analyses">
                            <span class="btn btn-pink"><i class="icon-upload icon-white"></i> Create New Analysis</span>
                        </a>
                    </li>

                  
                    <li id="site_nav_analyses">
                        <a href="/jobs" class="navigation-button navigation-analyses">
                            <span class="btn btn-pink"><i class="icon-inbox icon-white"></i> My Analyses</span>
                        </a>
                    </li>
                    <% if current_user -%>
                    <li id="site_nav_edit_profile">
                        <a href="/users/edit" class="navigation-button navigation-edit-profile">
                            <span class="btn"><i class="icon-user"></i> Edit Profile</span>
                        </a>
                    </li>

                    <li id="site_nav_logout">
                        <a href="/users/sign_out" class="navigation-button navigation-logout">
                            <span class="btn"><i class="icon-off"></i> Logout</span>
                        </a>
                    </li>
                  <% else -%>
                      <li id="site_nav_register">
                      <a href="/users/sign_up" class="navigation-button navigation-register"><span class="btn">Register</span></a></li>
                      <li id="site_nav_login">
                      <a href="/users/sign_in" class="navigation-button navigation-login"><span class="btn">Login</span></a></li>


                  <% end -%>
                </ul>

            </div>
        </div>
    </div>


    <!--main content-->
    <div class="clear"></div>
    <br/>


    <div class="stuff">

    <!-- flash -->
    <% if flash[:notice] -%>
      <div id="notice" class="attention-label"><%= notice %></div>
    <% end -%>
    <% if flash[:alert] -%>
      <div id="alert" class="attention-label"><%= alert %></div>
    <% end -%>
    <!-- end of flash -->

      <%= yield -%>
    </div>
</div>

<!--footer-->

<div class="clear"></div>

<div id="footer">
    <div class="upper_footer">
        <div class="footer_container" align="center">


            <ul class="footer_links" align="center">
                <a href="http://www.statoil.com" target="_blank"><img src="/assets/img/logos/statoil.png" height="80px" alt="StatOil"/></a>
            </ul>

            <ul class="footer_links padRight40" align="center">
                <a href="http://www.ox.ac.uk/" target="_blank"><img src="/assets/img/logos/oxford.png" height="70px" alt="Oxford University"/></a>
            </ul>


            <ul class="footer_links" align="center">
                <a href="http://www.biodiversity.ox.ac.uk/" target="_blank"><img src="/assets/img/logos/biodiversity.png" height="70px" alt="BioDiversity Institute"/></a>
            </ul>

            <ul class="footer_links" align="center">
                <a href="http://www.oerc.ox.ac.uk/" target="_blank"><img src="/assets/img/logos/oerc.jpeg" height="70px" alt="Oxford e-Research Center"/></a>
            </ul>


        </div>
    </div>

    <div class="bottom_footer">
        <div class="footer_container">
            <div class="additional-information" align="center">
              <!-- <img src="/assets/img/left-sml.png" height="40px" alt="LEFT"/><br/> -->
                <a href="/privacy-policy">Terms and Conditions</a> | <a href="">Contact</a> |
                © University of Oxford 2012, layout designed by <a href="http://www.antarctic-design.co.uk" target="_blank">Antarctic
                Design</a>
            </div>
        </div>
    </div>
</div>


</body>
</html>

app/views/layouts/oboe.html.erb
<html lang="en">
<head>
  <title>OBOE | Oxford Batch Operation Engine</title>
  <meta charset="utf-8">
  <meta name="keywords" content="Vibrant,OeRC" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <meta property="og:type" content="OBOE"/>
  <meta property="og:site_name" content="OBOE"/>
  <meta property="og:description" content="OBOE"/>

  <%= javascript_include_tag :defaults -%>

  <% if controller.controller_name == 'accounts' and controller.action_name == 'edit' -%>
    <%= stylesheet_link_tag "jquery-ui-timepicker-addon.css" %>
    <%= javascript_include_tag 'jquery-ui-timepicker-addon' -%>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.7.1/themes/base/jquery-ui.css" type="text/css"/>
  <% end -%>

  <% if controller.controller_name == 'info' and controller.action_name == 'welcome' -%>
    <script type="text/javascript">
      var jobInformation = <%= Job.information.to_json.html_safe -%>;
    </script>
    <script type="text/javascript" src="/assets/js/service-parser.js"></script>
    <script type="text/javascript" src="/assets/js/filter.js"></script>
    <script type="text/javascript" src="/assets/js/jquery-1.4.1-and-plugins.min.js"></script> 
    <script type="text/javascript" src="/assets/js/jquery-1.7.1-ui.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.7.1/themes/base/jquery-ui.css" type="text/css"/>
  <% end -%>

  <link rel="shortcut icon" href="/assets/img/favicon.ico">
  <link rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="/assets/css/style.css"/>
  <link rel="stylesheet" href="/assets/css/960.css"/>
  <link rel="stylesheet" href="/assets/css/bootstrap-elements.css"/>

 
  <%= csrf_meta_tag %>
  <%= gmaps_header(@headers).html_safe -%>


</head>

<body class="home">
<div id="container">
    <div id="hd">
        <div id="hd_bar"></div>
        <div id="hd_nav">
            <div id="hd_nav_wrapper" class="clearfix">
                <ul id="site_nav" class="clearfix">
                    <li id="site_nav_home" class="selected"><a href="/" class="trackedLink"><span class="label">About</span></a>
                    </li>

                    <li id="site_nav_myanalyses">
                        <a href="/jobs" class="navigation-button navigation-analyses"><span class="label">My Analyses</span></a>
                    </li>
                    <% if current_user -%>
                      <li id="site_nav_edit_profile">
                        <a href="/users/edit" class="navigation-button navigation-edit-profile"><span class="label">Edit Profile</span></a></li>
                    <li id="site_nav_logout"><a href="/users/sign_out" class="navigation-button navigation-logout"><span class="label">Logout</span></a></li>

                    <% else -%>
                      <li id="site_nav_register">
                      <a href="/users/sign_up" class="navigation-button navigation-register"><span class="label">Register</span></a></li>
                      <li id="site_nav_login">
                      <a href="/users/sign_in" class="navigation-button navigation-login"><span class="label">Login</span></a></li>

                    <% end -%>

<% if current_user.try(:admin?) -%>
  <li><%= link_to 'Jobs', show_all_path -%></li>
  <li class="admin-link"><a href='/users/list'>Users</a></li>
  <li class="admin-link"><a href='/stats'>Stats</a></li>
  <li class="admin-link"><a href='/accounts'>Accounts</a></li>
  <li class="admin-link"><a href='/sidekiq/scheduled'>Queue</a></li>
<% end -%>
<% if current_user -%>
<% if current_user.allowed?(current_user.email) -%>
  <li class="admin-link"><a href='/show_token'>Token</a></li>
<% end -%>
<% end -%>
                    
                </ul>

                <ul id="external_links" class="ext_nav">

                    <li>
                        <a href="http://www.oerc.ox.ac.uk" class="oerc_link" target="_blank"></a>
                    </li>
                    <li>
                        <a href="http://www.ox.ac.uk" class="univ_oxford_link" target="_blank"></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>

    <!--main content-->
    <% if flash[:notice] -%>
      <div id="notice" class="attention-label"><%= notice %></div>
    <% end -%>
    <% if flash[:alert] -%>
      <div id="alert" class="attention-label"><%= alert %></div>
    <% end -%>

    <div class="stuff">
    <%= yield %>
    </div>

</div>

<!--footer-->

<div class="clear"></div>

<div id="footer">
    <div class="upper_footer">
        <div class="footer_container">
            <h4 id="additionalLinks">Additional OBOE Links</h4>

            <ul class="footer_links">
                <h4>Supported by</h4>
                <li><a href="http://vbrant.eu"><img src="/assets/img/services/sponsors/vibrant.png" alt="ViBRANT" width="90"/></a></li>
            </ul>

            <ul class="footer_links">
                <h4>Additional Links</h4>
                <li><a href="http://www.ox.ac.uk" target="_blank">Oxford University</a></li>
                <li><a href="http://www.oerc.ox.ac.uk" target="_blank">Oxford e-Research Centre</a></li>
            </ul>

            <ul class="footer_links">
                <h4>Documentation</h4>
                <li><a href="/faq">FAQ</a></li><br>
                <li><a href="/privacy-policy">Privacy Policy</a></li>
            </ul>

            <ul class="footer_links">
                <h4>Contact Us</h4>
                <li><a href="mailto:neil.caithness@oerc.ox.ac.uk?subject=OBOE">Email</a></li>
            </ul>
        </div>
    </div>

    <div class="bottom_footer">
        <div class="footer_container">
            <div class="additional-information" align="center">
                © University of Oxford 2012, layout designed by <a href="http://www.antarctic-design.co.uk" target="_blank">Antarctic Design</a>
            </div>
        </div>
    </div>
</div>


</body>
</html>

app/views/layouts/test.html.erb
<!DOCTYPE  html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-gb">

<head>
  <title>OeRC Batch Operation Engine</title>
  <meta name="keywords" content="Vibrant,OeRC" />
  <%= stylesheet_link_tag "oxbluetwo/basic" , :media => 'all'%>
  <%= stylesheet_link_tag "oxbluetwo/layout", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "oxbluetwo/lookandfeel", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "oxbluetwo/mainnav", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "oxbluetwo/print", :media => 'print' %>
  <%= stylesheet_link_tag "oxbluetwo/table", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "oxbluetwo/custom", :media => 'screen,projection' %>
  <%= stylesheet_link_tag "jquery-ui-timepicker-addon.css" %>
  <%= stylesheet_link_tag "jquery-ui.css" %>
  <%= javascript_include_tag :defaults -%>
  <%= csrf_meta_tag %>
  <%= gmaps_header(@headers).html_safe -%>
</head>
<body>

<div id="all">

<div id="header">
</div> <!-- header div -->

<div id="content">

<% if flash[:notice] -%>
<p id="notice"><%= notice %></p>
<% end -%>
<% if flash[:alert] -%>
<p id="alert"><%= alert %></p>
<% end -%>

<%= yield %>

</div> <!-- content div -->

<div id="mainnav">

<ul class="hmenu">
<li><%= link_to 'Home',  :controller => '/info', :action => 'welcome'  -%></li>
<li><%= link_to 'My analyses', :controller => '/jobs', :action => 'index' -%></li>
<%= render 'devise/menu/registration_items' -%>
<%= render 'devise/menu/login_items' -%>
<% if current_user.try(:admin?) -%>
  <li><%= link_to 'Jobs', show_all_path -%></li>
  <li><a href='/users/list'>Users</a></li>
  <li><a href='/stats'>Stats</a></li>
  <li><a href='/accounts'>Accounts</a></li>
<% end -%>
<% if current_user -%>
<% if current_user.allowed?(current_user.email) -%>
  <li><a href='/show_token'>Token</a></li>
<% end -%>
<% end -%>

</ul>

</div> <!-- mainnav div -->

<div id="footer">
  &copy;  University of Oxford 2011
  <a id="vibrant-logo" href="http://vbrant.eu" title="ViBRANT Homepage"><img  alt ="ViBRANT Logo" src="/images/acquia_prosper_logo.png" /></a>
</div> 
  <!-- footer div ends -->
</div> <!-- all div ends -->


</body>
</html>