config/routes.rb
Vibrant::Application.routes.draw do

  resources :jobs
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :tokens,:only => [:create, :destroy]
  resources :accounts

  require 'sidekiq/web'
  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  root :to => "info#welcome" # a temporary redirection, should be to welcome

  post 'jobs/search(.:format)', :to => 'jobs#search'
  post 'left/view/:id', :to => 'jobs#leftstream'
  get 'left/view/:id', :to => 'jobs#leftstream'

  post 'jobs/new', :to => 'jobs#new'
  post 'show_all', :to => 'jobs#show_all'
  post 'users/toggle/:id', :to => 'user#toggle_left'
  post 'accounts/arrears/:id', :to => 'accounts#toggle_arrears'
  post 'accounts/:id', :to => 'accounts#show'

  put  'jobs/recreate/:id(.:format)', :to => 'jobs#recreate'
  put  'delete/:id(.:format)', :to => 'jobs#destroy' # as delete doesn't seem to offer the ability to authenticate

  get  'jobs/new', :to => 'jobs#new'
  get  'jobs/new/:type', :to => 'jobs#new'
  get  'jobs/search(.:format)', :to => 'jobs#index'
  get  'download/:id', :to => 'jobs#download'
  get  'download/infile/:id', :to => 'jobs#get_infile'
  get  'download/coords/:id(.:format)', :to => 'jobs#download_coords'
  get  'show_all', :to => 'jobs#show_all'
  get  'show_token', :to => 'user#show_token'
  get  'change_token', :to => 'user#change_token'
  get  'users/list', :to => 'user#list_users'
  get  'users/show/:id', :to => 'user#show_user'
  post  'users/show/:id', :to => 'user#show_user'
  get  'users/find', :to => 'user#find_users'
  post  'users/find', :to => 'user#find_users'
  get  'stats', :to => 'user#stats'
  get 'jobs/toggle/:id', :to => 'jobs#toggle_public'
  get 'jobs/status/:id', :to => 'jobs#get_status'

  get  'routes', :to => 'info#routes'
  get  'docs', :to => 'info#docs'
  get  'left', :to => 'info#welcome'
  get  'home', :to => 'info#welcome'
  get  'privacy-policy', :to => 'info#privacy'
  get  'faq', :to => 'info#faq'
  get  'parameters/:type', :to => 'info#parameters'
  get  'types', :to => 'info#job_types'
  post  'types', :to => 'info#job_types'
  get  'information', :to => 'info#information'
  get  'undefined', :to => 'info#welcome'
  get  'inspect/:type/:id', :to => 'info#inspect'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404'
  end

end

app/models/account.rb
class Account
  include MongoMapper::Document

  key :name, String
  key :credits, Hash, :required => true
  key :expiry, Hash, :required => true
  key :totals, Hash, :required => true
  key :arrears, Hash, :required => true
  key :users, Array, :required => false
  timestamps!

  attr_accessor :name, :credits
  # default values
  before_validation :set_defaults, :on => :create

  def set_defaults
    self.credits = {}
    self.totals = {}
    self.expiry = {}
    self.arrears = {}
    Job.types.each_value do |v|
      self.credits[v] = 0
      self.totals[v] = 0
      self.expiry[v] = '31/06/2017'
      self.arrears[v] = 'yes'
    end
    return true
  end

  # add a new type to each account when it is added to the
  # application, using the console...
  # use a loop here...
  def new_job(type)
    self.credits[type] = 0
    self.totals[type] = 0
    self.expiry[type] = '31/06/2017'
    self.arrears[type] = 'yes'
  end

  # delete an entry, e.g. if job removed or renamed
  def del_job(type)
    self.credits.delete(type)
    self.totals.delete(type)
    self.expiry.delete(type)
    self.arrears.delete(type)
  end


  # recursive search of the jobs directory to find which jobs are running
  # on which machines
  # this should be in the job.rb file but there's a problem with the joint plugin
  def self.hostcheck(type)
    dropdir = "/storage/oboe/Jobs"
    hosts = Hash.new
    begin
      IO.readlines("#{dropdir}/#{type}/hosts.txt").each do |h|
        h.chomp!
        hosts[h] = Dir["#{dropdir}/**/*#{h}*"].length || 0
      end
      choice = hosts.sort {|a,b| a[1] <=> b[1]}[0][0] || "no_servers"
      return choice 
    rescue
      return "no_servers"
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all.sort {|x,y| x.name <=> y.name}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])
    @users = Array.new
    len = @account.users.length
    if len > 0
      0.upto(len -1) do |i|  
        u = User.find(@account.users[i])
        @users << u
      end
    end

    @selectopts = {}
    Job.types.each_pair do |k,v|
      if Rails.env.production?
        @selectopts[k] = v if Job.active?(v)
      else
        @selectopts[k] = v
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])

    # first find the users and set their accounts back to default
    default = Account.first(:name => "Default")
    @account.users.each do |u|
      begin
        user = User.find(u)
        user.account = default.id
        user.save
        default.users << user.id
      rescue
        Rails.logger.error("User #{u} cannot be found.")
      end
    end
    default.save

    # now the account may be safely destroyed
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :ok }
    end
  end

  # toggle arrears status
  # yes, I know I should be using ajax rather than re-rendering the entire page...
  def toggle_arrears
    if !current_user.admin?
      redirect_to :jobs and return
    end
    account = Account.find(params[:id])
    type = params[:type]
    if account.arrears[type] == 'no'
      account.arrears[type] = 'yes'
    elsif account.arrears[type] == 'yes'
      account.arrears[type] = 'no'
    end
    if account.save
      Rails.logger.error("SAVE succeeded")
      flash[:notice] = "#{account.name} arrears policy changed"
      redirect_to :controller => '/accounts', :action => 'show', :id => account.id
    else
      Rails.logger.error("SAVE failed")
      flash[:alert] = "#{account.name} arrears policy not changed"
      redirect_to :controller => '/accounts', :action => 'show', :id => account.id
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def expired?(date)
    if Time.now - (60 * 60 * 24) > Date.strptime(date, "%d/%M/%Y")
      return "#{date} - Expired"
    else
      return date
    end
  end

  def arrearcolour(flag)
    if flag == 'yes'
      return "#33CC33"
    else
      return "#FF3300"
    end
  end

  def arreartext(flag)
    if flag == 'yes'
      return "Yes"
    else
      return "No"
    end
  end

  def abuttong(flag)
    if flag == 'yes'
      return "btn btn-success"
    else
      return "btn btn-danger"
    end
  end

end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <% if !@account.credits.nil? -%>
  <div class="field">
  <%= f.fields_for :credits do |c| -%>
    <% @account.credits.each_pair do |k,v| -%>
      <br><b><%= k -%>: </b>
      <%= c.text_field k, :value => v -%>
    <% end -%>
  <% end -%>
  </div>
  <% end -%>

  <% if !@account.expiry.nil? -%>
  <div class="field">
  <%= f.fields_for :expiry do |e| -%>
    <% @account.expiry.each_pair do |k,v| -%>
      <br><b><%= k -%>: </b>
      <%= e.datepicker  k, :currentText => v, :value => v, :date => v -%>
    <% end -%>
  <% end -%>
  </div>
  <% end -%>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/approval_list.html.erb
<div class="oboe-services-header"><span class="content-section analyses-section"><span class="header-text">Listing accounts</span></span></div>

<table class="table table-condensed" cellpadding="2">
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><b><%= account.name %></b></td>
    <td><%= link_to 'Show', account %></td>
  </tr>
<% end %>
</table>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div class="oboe-services-header"><span class="content-section analyses-section"><span class="header-text">Listing accounts</span></span></div>

<table class="table table-condensed" cellpadding="2">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><b><%= account.name %></b></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p>
  <b>Name:</b>
  <%= @account.name %>
</p>


<div id="accountDetails">
<p>
  <table class="table table-condensed" cellpadding="2">
    <tr valign="top" class="ListLine0">
      <th>Type</th>
      <th>Total</th>
      <th>Credits</th>
      <th>Expiry</th>
      <th>Arrears?</th>
    </tr>

    <% 
      odd_or_even = 0
      @selectopts.each_pair do |k,v|
        odd_or_even = 1 - odd_or_even
    %>
      <tr valign="top" class="ListLine<%= odd_or_even -%>">  
        <td><%= k -%></td>
        <td><%= @account.totals[v] || "OMG ERROR" -%></td>
        <td><%= @account.credits[v] || "OMG ERROR" -%></td>
        <td><%= expired?(@account.expiry[v] || "15/04/1912") -%></td>
        <td><%= button_to arreartext(@account.arrears[v] || "no"), {:controller => '/accounts', :action => "toggle_arrears", :id => @account.id, :type => v}, :class => abuttong(@account.arrears[v]), :id => "#{@account.id}_#{v}" -%>  </td>
      </tr>
    <% end -%>
  </table>
</p>
</div>

<% if !@users -%>
  <b>Members:</b> None.
<% else -%>
<p>
  <b>Members:</b>
  <table class="table table-condensed" cellpadding="2">
    <tr valign="top" class="ListLine0">
      <th>Email</th>
      <th>Created</th>
      <th>Last login</th>
      <th>IP address</th>
      <th>Token enabled?</th>
      <th>Admin?</th>
    </tr>

    <% 
      odd_or_even = 0
      @users.each do |user| 
        odd_or_even = 1 - odd_or_even
        next if user.nil?
    %>
      <tr valign="top" class="ListLine<%= odd_or_even -%>">  
        <td><a href="/users/show/<%= user.id -%>"><%= user.email -%></a></td>
        <td><%= user.created_at %></td>
        <td><%= user.last_sign_in_at || "N/A" %></td>    
        <td><%= user.last_sign_in_ip || "N/A" %></td>    
        <td align="center"><%=  "<span class='label label-success'>yes</span>".html_safe if !user.authentication_token.nil? %></td>
        <td align="center"><%= "<span class='label label-success'>yes</span>".html_safe if user.admin == true %></td>
      </tr>
    <% end -%>
  </table>

</p>
<% end -%>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>